#:kivy 2.3.1

MDBoxLayout:
    orientation: 'horizontal'

    MDBoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.2

        MDLabel:
            size_hint_y: 0.3
            text: 'Logo goes here'
            halign: 'center'
        
        TextBoxes:
            graph_area: ccs 
            
        
        MDLabel:
            size_hint_y: 0.2
            text: 'settings_panel'
            halign: 'center'

    CartesianCoordinateSystem:
        id: ccs

