#:kivy 2.3.1

MDBoxLayout:
    orientation: 'horizontal'

    MDBoxLayout:
        orientation: 'vertical'
        size_hint_x: 0.3

        # MDLabel:
        #     size_hint_y: 0.3
        #     text: 'Logo goes here'
        #     halign: 'center'

        MDBoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: "60dp"
            padding: "20dp"

            MDIconButton:
                icon: 'plus-outline'
                icon_size: "26sp"
                pos_hint: {"center_x": 0.2, "center_y": 0.94}
                on_release: text_boxes.draw_text_boxes()

            Widget:

            MDIconButton:
                icon: 'cog-outline'
                theme_font_size: "Custom"
                font_size: "26sp"
                pos_hint: {"center_x": 1, "center_y": 0.94}

                    
        ScrollView: 
            do_scroll_x: False
            do_scroll_y: True

            TextBoxes:
                id: text_boxes
                ccs_obj: ccs 
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
                spacing: "10dp"
                padding: "10dp"


    CartesianCoordinateSystem:
        id: ccs

